CREATE TABLE customer (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL ,
    city varchar(255)
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price REAL CHECK (price > 0)
);

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    customer_id INT,
    product_id INT,
    quantity INT CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    FOREIGN KEY (customer_id)
                    REFERENCES customer(id),
    FOREIGN KEY (product_id)
                    REFERENCES products(id)
);

ALTER TABLE products
ALTER COLUMN price TYPE NUMERIC(10,2);

ALTER TABLE products
ALTER COLUMN price SET NOT NULL;

ALTER TABLE products
ADD CONSTRAINT price CHECK (price > 0 );

-- generated by ChatGPT
INSERT INTO customer (full_name, city)
VALUES
    ('Ivan Petrov', 'Moscow'),
    ('Anna Smirnova', 'Saint Petersburg'),
    ('John Smith', 'London'),
    ('Alice Brown', 'New York'),
    ('Bob Johnson', 'Berlin');

INSERT INTO products (title, price)
VALUES
    ('Laptop', 1200.50),
    ('Keyboard', 49.99),
    ('Mouse', 25.50),
    ('Monitor', 350.00),
    ('Headphones', 89.90);

INSERT INTO products (title, price)
VALUES
    ('Pen', 1.50);

INSERT INTO orders (customer_id, product_id, quantity)
VALUES
    (1, 1, 1), -- Ivan купил Laptop
    (1, 2, 2), -- Ivan купил 2 Keyboard
    (2, 3, 1), -- Anna купила Mouse
    (2, 5, 1), -- Anna купила Headphones
    (3, 4, 2), -- John купил 2 Monitor
    (4, 1, 1), -- Alice купила Laptop
    (4, 3, 3), -- Alice купила 3 Mouse
    (5, 2, 1), -- Bob купил Keyboard
    (5, 4, 1), -- Bob купил Monitor
    (5, 5, 2); -- Bob купил 2 Headphones

INSERT INTO customer (full_name, city)
VALUES
    ('Anushervon Bozorov', 'Dushanbe'),
    ('Muhammad Rahimov', 'Dushanbe'),
    ('Farzona Karimova', 'Dushanbe'),
    ('Jamshid Safarov', 'Dushanbe'),
    ('Nilufar Saidova', 'Dushanbe');

INSERT INTO customer (full_name, city)
VALUES
    ('Harry Potter', 'Hogwarts');

INSERT INTO orders (customer_id, product_id, quantity)
VALUES
    (6, 1, 1), -- Anushervon -> Laptop
    (6, 3, 2), -- Anushervon -> 2 Mouse

    (7, 2, 1), -- Muhammad -> Keyboard
    (7, 5, 1), -- Muhammad -> Headphones

    (8, 4, 2), -- Farzona -> 2 Monitor

    (9, 1, 1), -- Jamshid -> Laptop
    (9, 2, 1), -- Jamshid -> Keyboard
    (9, 3, 1), -- Jamshid -> Mouse

    (10, 5, 3); -- Nilufar -> 3 Headphones


-- Базовые выборки и фильтрация
--     Задание 1. Выведите список всех заказов. Результат должен содержать: ID заказа, имя клиента, название товара и количество.
    SELECT o.id AS oerder_id,
           c.full_name AS customer_name,
           p.title AS product_title,
           o.quantity
    FROM orders o
    JOIN customer c
        ON o.customer_id=c.id
    JOIN products p
        ON o.product_id=p.id;

--     Задание 2. Выведите все заказы клиентов из города "Dushanbe".
    SELECT o.id AS oerder_id,
           c.full_name AS customer_name,
           p.title AS product_title,
           o.quantity
    FROM orders o
    JOIN customer c
        ON o.customer_id=c.id
    JOIN products p
        ON o.product_id=p.id
    WHERE c.city='Dushanbe';

--     Задание 3. Выведите все товары дороже 500, отсортировав их по цене (по убыванию).
    SELECT *
    FROM products
    WHERE price > 500
    ORDER BY price;


-- Агрегация данных (COUNT, SUM, AVG)
--     Задание 4. Найдите количество заказов для каждого клиента (имя клиента, кол-во заказов).
    SELECT c.id,
           c.full_name,
           count(*) AS orders_quantity
    FROM orders o
    JOIN customer c ON o.customer_id = c.id
    GROUP BY  c.id, c.full_name
    ORDER BY orders_quantity DESC;

--     Задание 5. Найдите количество продаж каждого товара (название товара, кол-во заказов).
    SELECT p.id,
           p.title,
           COALESCE(
                   sum(o.quantity),
                   0) AS sold_count
    FROM orders o
    RIGHT JOIN products p ON o.product_id = p.id
    GROUP BY p.id, p.title
    ORDER BY sold_count DESC;

--     Задание 6. Найдите общую сумму каждого заказа (подсказка: quantity * price). Результат: ID заказа, клиент, товар, итоговая сумма.
    SELECT o.id AS order_id,
           c.full_name AS client_name,
           COALESCE(
                   round(
                           (o.quantity * p.price)::NUMERIC,
                           2),
                   0) AS total_sold_sum
    FROM orders o
    JOIN products p ON o.product_id = p.id
    JOIN customer c ON o.customer_id = c.id
    GROUP BY o.id, c.full_name, p.price
    ORDER BY o.id;

--     Задание 7. Найдите общую сумму покупок для каждого клиента (клиент, общая сумма потраченных денег).
    SELECT c.full_name AS client_name,
           COALESCE(
                   ROUND(
                           SUM((o.quantity * p.price)::NUMERIC),
                           2),
                   0) total_spent_sum
    FROM customer c
    LEFT JOIN orders o ON c.id = o.customer_id
    LEFT JOIN products p ON o.product_id = p.id
    GROUP BY c.id
    ORDER BY total_spent_sum DESC;


-- Работа с условиями и функциями
--     Задание 8. Выведите список клиентов, которые совершили более одного заказа.
    SELECT c.id AS client_id,
           c.full_name,
           count(o.id) AS client_order_count
    FROM customer c
    LEFT JOIN orders o ON c.id =  o.customer_id
    GROUP BY c.id
    HAVING count(o.id) > 1
    ORDER BY client_order_count DESC;

--     Задание 9. Найдите самый дорогой товар в базе данных, используя функцию MAX().
    SELECT *
    FROM products p
    WHERE p.price = (
        SELECT max(p.price)
        FROM products p
    );

--     Задание 10. Найдите среднюю стоимость всех товаров в магазине, используя функцию AVG()
    SELECT round(avg(p.price), 2)
    FROM products p;


-- Аналитика и ТОП-рейтинги
--     Задание 11. Найдите клиента, который совершил больше всего заказов (используйте COUNT(), ORDER BY и LIMIT).
    SELECT c.id AS client_id,
           c.full_name,
           count(o.id) AS client_order_count
    FROM customer c
    LEFT JOIN orders o ON c.id =  o.customer_id
    GROUP BY c.id
    ORDER BY client_order_count DESC
    LIMIT 1;

--     Задание 12. Выведите ТОП-5 клиентов по общей сумме их покупок.
    SELECT c.id AS client_id,
           c.full_name,
           COALESCE(
                   round(
                           sum(o.quantity * p.price)::NUMERIC,
                           2),
                   0) AS total_byed_sum
    FROM customer c
    LEFT JOIN orders o on c.id = o.customer_id
    JOIN products p on o.product_id = p.id
    GROUP BY c.id
    ORDER BY total_byed_sum DESC
    LIMIT 5;

--     Задание 13. Выведите список товаров, которые были заказаны более одного раза (используйте GROUP BY и COUNT()).
    SELECT p.id,
           p.title,
           count(o.id) AS count_of_order
    FROM orders o
    JOIN products p on p.id = o.product_id
    GROUP BY p.id
    HAVING count(o.id) > 1
    ORDER BY count_of_order DESC;

--     Задание 14. Найдите самый продаваемый товар (по суммарному количеству проданных единиц).
    SELECT p.id,
           p.title,
           sum(o.quantity) AS count_of_sold
    FROM orders o
    JOIN products p on p.id = o.product_id
    GROUP BY p.id
    ORDER BY count_of_sold DESC
    LIMIT 1;

--     Задание 15 ⭐. Сформируйте итоговый отчёт по клиентам. Для каждого клиента выведите:
--     имя клиента;
--         общее количество заказов;
--         общую сумму покупок;
--         средний чек.
--         Сортировка: по общей сумме покупок от большего к меньшему.
    SELECT c.id AS client_id,
           c.full_name AS client_name,
           count(o.id) AS count_of_orders,
           COALESCE(
                   round(
                           sum(o.quantity * p.price)::NUMERIC,
                           2),
                   0) AS total_byed_sum,
           COALESCE(
                   avg(o.quantity * p.price),
                   0) AS average_cost
    FROM customer c
    LEFT JOIN orders o on c.id = o.customer_id
    LEFT JOIN products p on o.product_id = p.id
    GROUP BY c.id
    ORDER BY total_byed_sum DESC;